### PR TITLE
CI: Upgrade Actions

### PR DESCRIPTION
**Pull request by jibeee**
Upgrade:

- actions/checkout to v3
- codecov/codecov-action to v3
- actions/setup-python to v4

Remove fast checks workflow, already covered by the pre-commit action checks.

### CODE REVIEW

**Comment by lpascal-ledger** [comment]
Pre-commit checks protects this repo from cooperative **and** pre-commit-conf-aware contributors.
Given the pre-commit configuration is not documented anywhere, contributors could propose flawed PR in good faith, and there would be no more checks to enforce those requirements.
And I'm not even talking about contributors who don't care about code smells.

**Review by lpascal-ledger — COMMENTED** [review]
Pre-commit checks protects this repo from cooperative and pre-commit-conf-aware contributors.
Given the pre-commit configuration is not documented anywhere, contributors could propose flawed PR in good faith, and there would be no more checks to enforce those requirements.
And I'm not even talking about contributors who don't care about code smells.

**Comment by jibeee** [comment]
Pre-commit set should indeed be documented.

However, checks are enforced on the CI side: an action runs the pre-commit checks. See <https://github.com/LedgerHQ/ledgerctl/blob/master/.github/workflows/pre-commit.yml>. That is why I deleted the fast-check workflow, which doubled with the other action.

**Review by lpascal-ledger — APPROVED** [review]

**Comment by danroc** [comment]
@lpascal-ledger and @jibeee, FYI, contributors are instructed to run `pre-commit` checks locally before submitting a pull-request:
https://github.com/LedgerHQ/ledgerctl#pre-commit-checks

**Comment by jibeee** [comment]
> @lpascal-ledger and @jibeee, FYI, contributors are instructed to run `pre-commit` checks locally before submitting a pull-request: https://github.com/LedgerHQ/ledgerctl#pre-commit-checks

Sorry, I didn't see you already documented it! We cannot assume contributors will always set `pre-commit` hooks, so running these checks on the CI (what you enabled) is also necessary.

**Pull request merged**
